/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projii.GUI;

import javax.swing.JScrollPane;

/**
 *
 * @author 41080130
 */
public class BaseJF extends javax.swing.JFrame {

    /**
     * Creates new form BaseJF
     */
    private String Usuario;

    public void setUsuario(String Usuario) {
        this.Usuario = Usuario;
    }
    private PLogin login;
    
    public BaseJF() {
        initComponents();
        this.setTitle("System Mack");
        this.setResizable(false);
        //callLogin();
        callManterUsuario();
    }
    protected void callManterUsuario(){
        ManterUsuario manterUsuario = new ManterUsuario();
        JScrollPane jScrollPane = new JScrollPane(manterUsuario);
        this.add(jScrollPane);
        
        jScrollPane.setVisible(true);
        //(800,600)
        jScrollPane.setLocation(50, 25);
        jScrollPane.setSize(700, 500);
    }            
    protected void atualizaUsr(){
        jMILogar.setText(this.Usuario);
    }            
    protected void callLogin(){
        jMILogar.setText("Login");
        login = new PLogin(this); 
        this.add(login);
        login.setVisible(true);
        //(800,600)
        login.setLocation(200, 100);
        login.setSize(400, 300);
    }            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMEditar = new javax.swing.JMenu();
        jMILogar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jMArquivo.setText("Arquivo");
        jMenuBar1.add(jMArquivo);

        jMEditar.setText("Editar");

        jMILogar.setText("Usuario");
        jMILogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILogarActionPerformed(evt);
            }
        });
        jMEditar.add(jMILogar);

        jMenuBar1.add(jMEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMILogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILogarActionPerformed
        callLogin();
    }//GEN-LAST:event_jMILogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseJF().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenu jMEditar;
    private javax.swing.JMenuItem jMILogar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}