/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projii.GUI;

import br.com.projii.controller.UsuarioController;
import br.com.projii.jpa.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dj002
 */
public class ManterUsuario extends javax.swing.JPanel {

    private UsuarioController usuarioController = null;

    /**
     * Creates new form ManterUsuario
     */
    public ManterUsuario() {
        initComponents();
        atualizarJTUsuarios();
        ajustaTablePreferences();

    }

    private void ajustaTablePreferences() {
        jTUsuarios.setSize(1500, 300);
        jTUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTUsuarios.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTUsuarios.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(6).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(8).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(9).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(10).setPreferredWidth(100);

    }

    public void atualizarJTUsuarios() {
        try {
            if (usuarioController == null) {
                usuarioController = new UsuarioController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        Usuario[] usuarios = usuarioController.findAll().toArray(new Usuario[0]);
        Object[][] objects = new Object[usuarios.length][11];
        for (int i = 0; i < usuarios.length; i++) {
            objects[i][0] = usuarios[i].getId();
            objects[i][1] = usuarios[i].getNome();
            objects[i][2] = usuarios[i].getSenha();
            objects[i][3] = usuarios[i].getEndereco();
            objects[i][4] = usuarios[i].getCep();
            objects[i][5] = usuarios[i].getSexo();
            objects[i][6] = usuarios[i].getEmail();
            objects[i][7] = usuarios[i].getTelefone();
            objects[i][8] = usuarios[i].getDataNasc();
            objects[i][9] = usuarios[i].getRG();
            objects[i][10] = usuarios[i].getCPF();
        }
        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                objects,
                new String[]{
                    "id", "Nome", "Senha", "Endereco", "CEP", "Sexo", "Email",
                    "Telefone", "Data Nasc", "RG", "CPF"
                }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jTFSenha = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jTFCep = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFRG = new javax.swing.JTextField();
        jTFCPF = new javax.swing.JTextField();
        jRBSexoM = new javax.swing.JRadioButton();
        jRBSexoF = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jBCadastrar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jRBFuncS = new javax.swing.JRadioButton();
        jRBFuncN = new javax.swing.JRadioButton();
        jDCData = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 400));
        setRequestFocusEnabled(false);

        jLabel1.setText("id");

        jLabel2.setText("nome");

        jLabel3.setText("senha");

        jLabel4.setText("endereco");

        jLabel5.setText("cep");

        jLabel6.setText("sexo");

        jLabel7.setText("email");

        jLabel8.setText("telefone");

        jLabel10.setText("RG");

        jLabel11.setText("CPF");

        jTFId.setEditable(false);

        jRBSexoM.setText("M");
        jRBSexoM.setSelected(true);
        jRBSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSexoMActionPerformed(evt);
            }
        });

        jRBSexoF.setText("F");
        jRBSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSexoFActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 280));

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "senha", "endereco", "cep", "sexo", "email", "telefone", "Data de Nascimento", "RG", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jLabel12.setText("É funcionario?");

        jRBFuncS.setText("S");
        jRBSexoM.setSelected(true);
        jRBFuncS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFuncSActionPerformed(evt);
            }
        });

        jRBFuncN.setText("N");
        jRBFuncN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFuncNActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de Nasc.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jBCadastrar)
                                    .addGap(300, 300, 300)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBFuncS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBFuncN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBSexoM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBSexoF))
                            .addComponent(jTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(530, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDCData, jTFCPF, jTFCep, jTFEmail, jTFEndereco, jTFId, jTFNome, jTFRG, jTFSenha, jTFTelefone});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCadastrar, jBExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRBSexoM)
                            .addComponent(jRBSexoF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDCData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBFuncS)
                                .addComponent(jRBFuncN))
                            .addComponent(jLabel12)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBExcluir)
                    .addComponent(jBAlterar)
                    .addComponent(jBLimpar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDCData, jTFCPF, jTFCep, jTFEmail, jTFEndereco, jTFId, jTFNome, jTFRG, jTFSenha, jTFTelefone});

    }// </editor-fold>//GEN-END:initComponents

    private void jRBSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSexoMActionPerformed
        jRBSexoF.setSelected(!jRBSexoM.isSelected());
    }//GEN-LAST:event_jRBSexoMActionPerformed
    private void limpaTxts() {
        jTFId.setText("");
        jTFNome.setText("");
        jTFSenha.setText("");
        jTFEndereco.setText("");
        jTFCep.setText("");
        jRBSexoM.setSelected(true);
        jRBSexoF.setSelected(false);
        jTFEmail.setText("");
        jTFTelefone.setText("");
        jDCData.setDate(new Date());
        jTFRG.setText("");
        jTFCPF.setText("");
    }
    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        // TODO add your handling code here:
        //botao alterar fica ativo
//        jbAlterar.setEnabled(true);
//        jbExcluir.setEnabled(true);
        // tabela ganha foco
        limpaTxts();
        Usuario u;
        try {
            if (usuarioController == null) {
                usuarioController = new UsuarioController();
            }
            Object id = jTUsuarios.getValueAt(jTUsuarios.getSelectedRow(), 0);
            u = usuarioController.find(id);
            jDCData.setDate(u.getDataNasc());
            if (u.isIsFunc()) {
                jRBFuncS.setSelected(true);
                jRBFuncN.setSelected(false);
            } else {
                jRBFuncS.setSelected(true);
                jRBFuncN.setSelected(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar o usuario");
        }
        int linha = jTUsuarios.getSelectedRow();

        //pegar conteudo da linha no banco de dados e jogar nos jtf
        if (!(jTUsuarios.getValueAt(linha, 0) == null)) {
            jTFId.setText(jTUsuarios.getValueAt(linha, 0).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 1) == null)) {
            jTFNome.setText(jTUsuarios.getValueAt(linha, 1).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 2) == null)) {
            jTFSenha.setText(jTUsuarios.getValueAt(linha, 2).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 3) == null)) {
            jTFEndereco.setText(jTUsuarios.getValueAt(linha, 3).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 4) == null)) {
            jTFCep.setText(jTUsuarios.getValueAt(linha, 4).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 5) == null)) {
            if (jTUsuarios.getValueAt(linha, 5).toString().equals("F")) {
                jRBSexoM.setSelected(false);
                jRBSexoF.setSelected(true);
            } else {
                jRBSexoM.setSelected(true);
                jRBSexoF.setSelected(false);
            }
        }
        if (!(jTUsuarios.getValueAt(linha, 6) == null)) {
            jTFEmail.setText(jTUsuarios.getValueAt(linha, 6).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 7) == null)) {
            jTFTelefone.setText(jTUsuarios.getValueAt(linha, 7).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 9) == null)) {
            jTFRG.setText(jTUsuarios.getValueAt(linha, 9).toString());
        }
        if (!(jTUsuarios.getValueAt(linha, 10) == null)) {
            jTFCPF.setText(jTUsuarios.getValueAt(linha, 10).toString());
        }

    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jRBSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSexoFActionPerformed
        jRBSexoM.setSelected(!jRBSexoF.isSelected());
    }//GEN-LAST:event_jRBSexoFActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpaTxts();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jRBFuncSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFuncSActionPerformed
        jRBFuncN.setSelected(!jRBFuncS.isSelected());
    }//GEN-LAST:event_jRBFuncSActionPerformed

    private void jRBFuncNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFuncNActionPerformed
        jRBFuncS.setSelected(!jRBFuncN.isSelected());
    }//GEN-LAST:event_jRBFuncNActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        Usuario usuario = null;
        try {
            usuario = new Usuario(jTFNome.getText(), jTFSenha.getText());
            usuario.setCPF(Long.parseLong(jTFCPF.getText()));
            usuario.setCep(Long.parseLong(jTFCep.getText()));
            usuario.setDataNasc(jDCData.getDate());
            usuario.setEmail(jTFEmail.getText());
            usuario.setEndereco(jTFEndereco.getText());
            if (jRBFuncS.isSelected()) {
                usuario.setIsFunc(true);
            } else {
                usuario.setIsFunc(false);
            }
            usuario.setTelefone(jTFTelefone.getText());
            usuario.setRG(Long.parseLong(jTFRG.getText()));
            if (jRBSexoM.isSelected()) {
                usuario.setSexo('M');
            } else {
                usuario.setSexo('F');
            }
            try {
                if (usuarioController == null) {
                    usuarioController = new UsuarioController();
                }
                usuarioController.create(usuario);
                atualizarJTUsuarios();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao gravar usuario: " + usuario);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Formulario mal preenchido",
                    "System Mack", 2);
        }

        limpaTxts();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            if (usuarioController == null) {
                usuarioController = new UsuarioController();
            }
            Object id = jTUsuarios.getValueAt(jTUsuarios.getSelectedRow(), 0);
            Usuario u = usuarioController.find(id);
            usuarioController.delete(u);
            atualizarJTUsuarios();
            limpaTxts();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar o usuario");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        Usuario usuario = null;
        try {
            if (usuarioController == null) {
                usuarioController = new UsuarioController();
            }
            Object id = jTUsuarios.getValueAt(jTUsuarios.getSelectedRow(), 0);
            usuario = usuarioController.find(id);

            usuario.setNome(jTFNome.getText());
            usuario.setSenha(jTFSenha.getText());
            usuario.setCPF(Long.parseLong(jTFCPF.getText()));
            usuario.setCep(Long.parseLong(jTFCep.getText()));
            usuario.setDataNasc(jDCData.getDate());
            usuario.setEmail(jTFEmail.getText());
            usuario.setEndereco(jTFEndereco.getText());
            if (jRBFuncS.isSelected()) {
                usuario.setIsFunc(true);
            } else {
                usuario.setIsFunc(false);
            }
            usuario.setRG(Long.parseLong(jTFRG.getText()));
            usuario.setTelefone(jTFTelefone.getText());
            if (jRBSexoM.isSelected()) {
                usuario.setSexo('M');
            } else {
                usuario.setSexo('F');
            }
            try {
                usuarioController.update(usuario);
                atualizarJTUsuarios();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao Alterar o usuario");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Formulario mal preenchido",
                    "System Mack", 2);
        }
        limpaTxts();
    }//GEN-LAST:event_jBAlterarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBLimpar;
    private com.toedter.calendar.JDateChooser jDCData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBFuncN;
    private javax.swing.JRadioButton jRBFuncS;
    private javax.swing.JRadioButton jRBSexoF;
    private javax.swing.JRadioButton jRBSexoM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCPF;
    private javax.swing.JTextField jTFCep;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFRG;
    private javax.swing.JTextField jTFSenha;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
