/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projii.GUI;

import br.com.projii.controller.ItemPedidoController;
import br.com.projii.controller.PedidoController;
import br.com.projii.controller.ProdutoController;
import br.com.projii.jpa.ItemPedido;
import br.com.projii.jpa.Pedido;
import br.com.projii.jpa.Produto;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dj002
 */
public class CheckOut extends javax.swing.JPanel {

    private PedidoController pedidoController = null;
    private ItemPedidoController itemPedidoController = null;
    private ProdutoController produtoController = null;
    private static final Font COURIER_NEW = new Font("Courier New", 
            Font.PLAIN, 11);

    /**
     * Creates new form EfetuarCompra
     */
    public CheckOut(long idPedido) {
        initComponents();
        atualizaJTAPedido(idPedido);
    }

    public void atualizaJTAPedido(long idPedido) {
        try {
            if (pedidoController == null) {
                pedidoController = new PedidoController();
            }
            if (itemPedidoController == null) {
                itemPedidoController = new ItemPedidoController();
            }
            if (produtoController == null) {
                produtoController = new ProdutoController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }

        Pedido pedido = pedidoController.find(idPedido);
        List<ItemPedido> itensPedido = itemPedidoController.findAll();
        String s = pedido.toString();
        double total = 0;
        for (ItemPedido itemPedido : itensPedido) {
            if (itemPedido.getPedido().getId().equals(pedido.getId())) {
                Produto produto = produtoController.find(itemPedido.getIdProduto());
                s = s + "\n" + itemPedido.toString();
//                s = s + "\n" + produto.toString();


                if (produto.getNome().length() < 16) {
                    int i = 16 - produto.getNome().length();
                    s = s + "\n" + produto.getNome();
                    for (int j = 0; j < i; j++) {
                        s = s + ".";
                    }
//                    System.out.format("%10.3f%n", pi);
                    s = s + ".....:" + String.format("%10.3f", produto.getPreco());
                    s = s + ".....:" + String.format("%10.3f", produto.getPreco() * itemPedido.getQtde());
                    total = total + produto.getPreco() * itemPedido.getQtde();
                } else {
                    s = s + "\n" + produto.getNome().substring(0, 15);
//                    s = s + ".....:" + produto.getPreco() * itemPedido.getQtde();
//                    total = total + produto.getPreco() * itemPedido.getQtde();
//                    s = s + ".....:" + produto.getPreco();
                    s = s + ".....:" + String.format("%10.3f", produto.getPreco());
                    s = s + ".....:" + String.format("%10.3f", produto.getPreco() * itemPedido.getQtde());
                    total = total + produto.getPreco() * itemPedido.getQtde();

                }
            }
        }
        s = s + "\nTotal:...............:" + String.format("%10.3f", total);
        jTAPedido.setText(s);
        jTAPedido.setFont(COURIER_NEW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBImprimir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAPedido = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(490, 400));
        setRequestFocusEnabled(false);

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jLabel10.setText("Venda Finalizada");

        jTAPedido.setColumns(20);
        jTAPedido.setRows(5);
        jScrollPane1.setViewportView(jTAPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImprimir)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
    }//GEN-LAST:event_jBImprimirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImprimir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAPedido;
    // End of variables declaration//GEN-END:variables
}
