/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projii.GUI;

import br.com.projii.controller.CategoriaController;
import br.com.projii.controller.ProdutoController;
import br.com.projii.jpa.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author dj002
 */
public class FecharVendas extends javax.swing.JPanel {

    private ProdutoController produtoController = null;
    private CategoriaController categoriaController = null;

    /**
     * Creates new form EfetuarCompra
     */
    public FecharVendas() {
        initComponents();
        atualizarJTProduto();
        ajustaTablePreferences();
    }

    private void ajustaTablePreferences() {
//        jTProduto.setSize(1500, 300);
//        jTProduto.getColumnModel().getColumn(0).setPreferredWidth(40);
//        jTProduto.getColumnModel().getColumn(1).setPreferredWidth(80);
//        jTProduto.getColumnModel().getColumn(2).setPreferredWidth(60);
//        jTCart.getColumnModel().getColumn(0).setPreferredWidth(40);
//        jTCart.getColumnModel().getColumn(1).setPreferredWidth(100);
//        jTCart.getColumnModel().getColumn(2).setPreferredWidth(60);
//        jTCart.getColumnModel().getColumn(3).setPreferredWidth(40);

    }

    public void atualizarJTProduto() {
        try {
            if (produtoController == null) {
                produtoController = new ProdutoController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        Produto[] filiais = produtoController.findAll().toArray(new Produto[0]);
        Object[][] objects = new Object[filiais.length][3];
        for (int i = 0; i < filiais.length; i++) {
            objects[i][0] = filiais[i].getId();
            objects[i][1] = filiais[i].getNome();
            objects[i][2] = filiais[i].getPreco();
        }
////        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
//                objects,
//                new String[]{
//            "id", "Nome", "Preço"
//        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBImprimir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTARelatorio = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(490, 400));
        setRequestFocusEnabled(false);

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jLabel10.setText("Relatório de vendas diárias:");

        jTARelatorio.setColumns(20);
        jTARelatorio.setRows(5);
        jScrollPane1.setViewportView(jTARelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImprimir)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
    }//GEN-LAST:event_jBImprimirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImprimir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTARelatorio;
    // End of variables declaration//GEN-END:variables
}
